name: Nightly builds - pyinstaller develop

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/test_pre_release_pyinstaller'

jobs:
  pyinstaller:
    if: "github.repository == 'qutebrowser/qutebrowser'"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            args:
            toxenv: build-release-qt6
            name: qt6-macos-debug
          - os: windows-2019
            args: --64bit
            toxenv: build-release-qt6
            name: qt6-windows-64bit-debug
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
            python -m pip install -U pip
            python -m pip install -U -r misc/requirements/requirements-tox.txt
      - name: Patch qutebrowser for debugging
        if: "contains(matrix.args, '--debug')"
        run: |
          sed -i '' '/.-d., .--debug.,/s/$/ default=True,/' qutebrowser/qutebrowser.py
      - name: Run tox
        run: "tox -e ${{ matrix.toxenv }} -- --gh-token ${{ secrets.GITHUB_TOKEN }} ${{ matrix.args }}"
      - name: Gather info
        id: info
        run: |
            echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
            echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "qutebrowser-nightly-pyinstaller-test-${{ steps.info.outputs.date }}-${{ steps.info.outputs.sha_short }}-${{ matrix.name }}"
          path: |
            dist/qutebrowser-*.dmg
            dist/qutebrowser-*-windows-standalone-*.zip
            dist/qutebrowser-*-*.exe
          if-no-files-found: error
      #- name: Upload dist on failure
      #  uses: actions/upload-artifact@v3
      #  if: "failure()"
      #  with:
      #    name: "qutebrowser-nightly-pyinstaller-test-failure-${{ steps.info.outputs.date }}-${{ steps.info.outputs.sha_short }}-${{ matrix.name }}"
      #    path: |
      #      dist/
      #      !dist/qutebrowser.app/Contents/Frameworks # duplicate of Resources
      #      !dist/qutebrowser/_internal/ # intermediate? seems to be the same as in Resources too
      #    if-no-files-found: error

